name: CD

on:
  workflow_dispatch: # allow jobs manual run
  release:
    types: [published]

jobs:
  send-to-telegram:
    name: send file to telegram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: make gradle executable
        run: chmod +x ./android/gradle

      - name: generate apk
        run: |
          cd android
          ./gradlew bundleRelease
          cd ..

      # -name: send apk to tele
      #   run: |
      # curl -F "file=@android/app/build/outputs/apk/release/app-release.apk" -F "token=${TELE_TOKEN}" https://api.telegram.org/bot${TELE_BOT_TOKEN}/sendDocument

      # curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=@app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument
